[window]
padding = { x = 8, y = 8 }
opacity = 0.8

[font]
normal.family = "Iosevka Fixed"
bold.family = "Iosevka Fixed"
italic.family = "Iosevka Fixed"
bold_italic.family = "Iosevka Fixed"

size = 15

[colors.primary]
foreground = "#c1c1c1"
background = "#000000"

[colors.normal]
black   = "#121212"
red     = "#333333"
green   = "#79241f"
yellow  = "#eeeeee"
blue    = "#79241f"
magenta = "#333333"
cyan    = "#666666"
white   = "#eeeeee"

[colors.bright]
black   = "#121212"
red     = "#333333"
green   = "#79241f"
yellow  = "#eeeeee"
blue    = "#79241f"
magenta = "#333333"
cyan    = "#666666"
white   = "#eeeeee"
