[window]
padding = { x = 8, y = 8 }
opacity = 0.8

[font]
normal.family = "Iosevka Fixed"
bold.family = "Iosevka Fixed"
italic.family = "Iosevka Fixed"
bold_italic.family = "Iosevka Fixed"

size = 16.0

[colors.primary]
foreground = "#c1c1c1"
background = "#000000"

[colors.normal]
black   = "#121212"
red     = "#333333"
green   = "#666666"
yellow  = "#eeeeee"
blue    = "#a7aa1e"
magenta = "#6a6c4c"
cyan    = "#a7aa1e"
white   = "#eeeeee"
