set -g default-terminal "screen-256color"
set -g prefix C-SPACE
set -g base-index 1
set -g renumber-windows on
set -g mode-keys vi
set -g status-position bottom
set -g status-justify absolute-centre
set -g status-style "bg=default"
set -g window-status-current-style "fg=green bold"
set -g status-right ""
set -g mouse on

bind r source-file ~/.config/tmux/tmux.conf
bind E show-environment -g

bind v split-window -h
bind s split-window -v

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5
